function y = interpolate2d(x, readPos)
    % Get the indices of the elements we need from the input.
    nx = floor(readPos(1));
    ny = floor(readPos(2));
    % Create a vector of the indices needed for interpolation. 
    readIndicesX = [nx, nx+1];
    readIndicesY = [ny, ny+1];
    % Get the fractional part of the read indices.
    alphax = mod(readPos(1), 1);
    alphay = mod(readPos(2), 1);
    % Calculate the coefficients.
    coeffs = [ ...
        (1 - alphax)*(1 - alphay); ...
        (1 - alphax)*alphay; ...
        alphax*(1 - alphay); ...
        alphax*alphay ...
    ];

    y = x(nx, ny) * coeffs(1) + ...
        x(nx, ny+1) * coeffs(2) + ...
        x(nx+1, ny) * coeffs(3) + ...
        x(nx+1, ny+1) * coeffs(4);
end